### ISSUE TITLE
[BUG] Not working on mac

### ISSUE THREAD

**Issue by dsabharwal326** [jbsparrow/CyberDropDownloader#164]
MacOS 14.1 Sonoma

So there was just a fix put out but now I'm getting this error:

ERROR: File 'AppData/Configs/Config/settings.yaml' has an invalid config. Please verify and edit it manually
   in "<unicode string>", line 49, column 16:
      scan_folder: !!python/object/apply:pathlib.Po ... 
                   ^

**Comment by jbsparrow** [comment]
The default config file was corrupted. The `scan_folder` value is invalid.

To fix it, please edit it manually and remove `!!python....` from `scan_folder`

Before:
```yaml
Sorting:
  scan_folder: !!python/object/apply:pathlib.Po
  - None
  sort_cdl_only: true
```
After:
```yaml
Sorting:
  scan_folder: None
  sort_cdl_only: true
```

The default config_file is located at `./AppData/Configs/Default/settings.yaml`
